controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController


forward_position_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
    interface_name: effort