controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    agv_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: diff_drive_controller/DiffDriveController


agv_controller:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.442
    wheel_radius: 0.075

    use_stamped_vel: false
    right_wheel_radius_multiplier: -1.0

    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.5

    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.0

